// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scalefocus_HobbyAPI_Database.Data;

#nullable disable

namespace Scalefocus_HobbyAPI_Database.Migrations
{
    [DbContext(typeof(ScalefocusDbContext))]
    [Migration("20250804092849_AddRefreshTokenTable")]
    partial class AddRefreshTokenTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.Associations.EventParticipants", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("EventParticipants");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            UserId = new Guid("3bae1d94-7392-477e-922e-e656a8597661"),
                            JoinedAt = new DateTime(2024, 6, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1
                        },
                        new
                        {
                            EventId = 1,
                            UserId = new Guid("7e61f925-b7d6-4e69-bbc2-a6695e2e424f"),
                            JoinedAt = new DateTime(2024, 6, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0
                        },
                        new
                        {
                            EventId = 2,
                            UserId = new Guid("7e61f925-b7d6-4e69-bbc2-a6695e2e424f"),
                            JoinedAt = new DateTime(2024, 7, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1
                        });
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.Associations.EventTasks", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("TasksId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("EventId", "TasksId");

                    b.HasIndex("TasksId");

                    b.ToTable("EventTasks");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            TasksId = 1,
                            AddedAt = new DateTime(2024, 6, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0
                        },
                        new
                        {
                            EventId = 1,
                            TasksId = 2,
                            AddedAt = new DateTime(2024, 6, 15, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            Role = 0
                        },
                        new
                        {
                            EventId = 2,
                            TasksId = 3,
                            AddedAt = new DateTime(2024, 8, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 2
                        },
                        new
                        {
                            EventId = 2,
                            TasksId = 4,
                            AddedAt = new DateTime(2024, 8, 14, 17, 5, 0, 0, DateTimeKind.Unspecified),
                            Role = 1
                        });
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.Associations.HobbyUser", b =>
                {
                    b.Property<int>("HobbiesId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("HobbiesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("HobbyUser");

                    b.HasData(
                        new
                        {
                            HobbiesId = 1,
                            UserId = new Guid("3bae1d94-7392-477e-922e-e656a8597661"),
                            CreatedAt = new DateTime(2024, 1, 2, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            HobbiesId = 2,
                            UserId = new Guid("7e61f925-b7d6-4e69-bbc2-a6695e2e424f"),
                            CreatedAt = new DateTime(2024, 2, 2, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            HobbiesId = 1,
                            UserId = new Guid("7e61f925-b7d6-4e69-bbc2-a6695e2e424f"),
                            CreatedAt = new DateTime(2024, 1, 5, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.Associations.TaskUser", b =>
                {
                    b.Property<int>("TasksId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TasksId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskUser");

                    b.HasData(
                        new
                        {
                            TasksId = 1,
                            UserId = new Guid("3bae1d94-7392-477e-922e-e656a8597661"),
                            CreatedAt = new DateTime(2024, 6, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false
                        },
                        new
                        {
                            TasksId = 2,
                            UserId = new Guid("7e61f925-b7d6-4e69-bbc2-a6695e2e424f"),
                            CreatedAt = new DateTime(2024, 6, 21, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false
                        });
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.Associations.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            UserId = new Guid("3bae1d94-7392-477e-922e-e656a8597661")
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = new Guid("7e61f925-b7d6-4e69-bbc2-a6695e2e424f")
                        });
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.CommentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Looking forward to this event!",
                            CreatedAt = new DateTime(2024, 6, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            UserId = new Guid("3bae1d94-7392-477e-922e-e656a8597661")
                        },
                        new
                        {
                            Id = 2,
                            Content = "Count me in!",
                            CreatedAt = new DateTime(2024, 6, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            UserId = new Guid("7e61f925-b7d6-4e69-bbc2-a6695e2e424f")
                        },
                        new
                        {
                            Id = 3,
                            Content = "Excited to learn painting.",
                            CreatedAt = new DateTime(2024, 7, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 2,
                            UserId = new Guid("7e61f925-b7d6-4e69-bbc2-a6695e2e424f")
                        });
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HobbyId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("ParticipantIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("OwnerId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("3bae1d94-7392-477e-922e-e656a8597661"),
                            Description = "A friendly chess tournament.",
                            EndDate = new DateTime(2024, 7, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            HobbyId = 1,
                            Location = "Community Center",
                            OwnerId = new Guid("3bae1d94-7392-477e-922e-e656a8597661"),
                            StartDate = new DateTime(2024, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Chess Tournament"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 15,
                            CreatedAt = new DateTime(2024, 7, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("7e61f925-b7d6-4e69-bbc2-a6695e2e424f"),
                            Description = "Learn to paint with watercolors.",
                            EndDate = new DateTime(2024, 8, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            HobbyId = 2,
                            Location = "Art Studio",
                            OwnerId = new Guid("7e61f925-b7d6-4e69-bbc2-a6695e2e424f"),
                            StartDate = new DateTime(2024, 8, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Painting Workshop"
                        });
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.Hobbies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Updated_at")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chess",
                            Updated_at = 20240101
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Painting",
                            Updated_at = 20240201
                        });
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "user"
                        });
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Arrange all chess boards and pieces before the tournament starts.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2024, 6, 30, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Set up chess boards"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Print and distribute score sheets for all matches.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2024, 6, 30, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Prepare score sheets"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Purchase watercolors, brushes, and paper for the workshop.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2024, 8, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Buy painting supplies"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Arrange easels and workspaces for participants.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2024, 8, 14, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Set up easels"
                        });
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3bae1d94-7392-477e-922e-e656a8597661"),
                            Email = "alice.smith@example.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            PasswordHash = "hash1",
                            Username = "alice123"
                        },
                        new
                        {
                            Id = new Guid("7e61f925-b7d6-4e69-bbc2-a6695e2e424f"),
                            Email = "bob.johnson@example.com",
                            FirstName = "Bob",
                            LastName = "Johnson",
                            PasswordHash = "hash2",
                            Username = "bob456"
                        });
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.Associations.EventParticipants", b =>
                {
                    b.HasOne("Scalefocus_HobbyAPI_Database.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scalefocus_HobbyAPI_Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.Associations.EventTasks", b =>
                {
                    b.HasOne("Scalefocus_HobbyAPI_Database.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scalefocus_HobbyAPI_Database.Models.TaskEntity", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.Associations.HobbyUser", b =>
                {
                    b.HasOne("Scalefocus_HobbyAPI_Database.Models.Hobbies", null)
                        .WithMany()
                        .HasForeignKey("HobbiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scalefocus_HobbyAPI_Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.Associations.TaskUser", b =>
                {
                    b.HasOne("Scalefocus_HobbyAPI_Database.Models.TaskEntity", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scalefocus_HobbyAPI_Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.Associations.UserRole", b =>
                {
                    b.HasOne("Scalefocus_HobbyAPI_Database.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scalefocus_HobbyAPI_Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.CommentEntity", b =>
                {
                    b.HasOne("Scalefocus_HobbyAPI_Database.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.Event", b =>
                {
                    b.HasOne("Scalefocus_HobbyAPI_Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scalefocus_HobbyAPI_Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Scalefocus_HobbyAPI_Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.RefreshToken", b =>
                {
                    b.HasOne("Scalefocus_HobbyAPI_Database.Models.User", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("Scalefocus_HobbyAPI_Database.Models.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scalefocus_HobbyAPI_Database.Models.User", b =>
                {
                    b.Navigation("RefreshToken");
                });
#pragma warning restore 612, 618
        }
    }
}
